//파일마다 import해서 불러오는 공간
//import './jsxstudy.js'
// import './first-component.js'
// import './animal-container.js'
// import './props-basic'
// import './sol_greeting'
// import './person-profile'
// import './props-children'
// import './sol_slot_machine'
// import './state-study-1'
// import './sol_user_profile'
//import './state-study-3'
// import './counter-with-hook-caveat'
// import './counter-demo'
// import './manipulate-list'
// import './todo-app-demo'
// import './shopping-cart'
// import './cart-app'
// import './use-effect-deps'
// import './use-effect-using-local-storage.js'
// import './use-effect-unmount'
// import './use-effect-unmount-deps'
// import './use-effect-with-dom.js'
// import './timer-demo'
// import './github-fetch-repos'
//import './github-user-search-app'
// import './kanye-west-api'
import './ref-demo.js'